### ISSUE TITLE
Фильтрация, поиск, сортировка и пагинация на сервере для таблицы Shops

### ISSUE THREAD

**Issue by akurutin** [single-project/spocr-core-service-ui-desktop#1]
Добавил кнопки очистки фильтров включая запрос на сервер, искал как программно очистить autocomplete компоненту

добавил подобный функционал на все остальные таблицы counterparty, manufacturer shopTypes

**Comment by andreyfomin** [comment]
починил поиск по контрагентам в таблице shop-data, подготовил для Гены пример как собрать измененные данные с реактивной формы
