### ISSUE TITLE
Не могу создать шоп

### ISSUE THREAD

**Issue by cyclon-b** [single-project/spocr-core-service-ui-desktop#26]
Кидаю POST 
{"name":"Test","shopTypes":[{"id":4}],"counterparty":{"id":1},"active":true,"address":{"id":null,"version":null,"active":null,"address":"г Ростов-на-Дону","comment":"Test","suggestion":{"value":"г Ростов-на-Дону","unrestricted_value":"Ростовская обл, г Ростов-на-Дону","data":{"postal_code":null,"country":"Россия","country_iso_code":"RU","federal_district":null,"region_fias_id":"f10763dc-63e3-48db-83e1-9c566fe3092b","region_kladr_id":"6100000000000","region_iso_code":"RU-ROS","region_with_type":"Ростовская обл","region_type":"обл","region_type_full":"область","region":"Ростовская","area_fias_id":null,"area_kladr_id":null,"area_with_type":null,"area_type":null,"area_type_full":null,"area":null,"city_fias_id":"c1cfe4b9-f7c2-423c-abfa-6ed1c05a15c5","city_kladr_id":"6100000100000","city_with_type":"г Ростов-на-Дону","city_type":"г","city_type_full":"город","city":"Ростов-на-Дону","city_area":null,"city_district_fias_id":null,"city_district_kladr_id":null,"city_district_with_type":null,"city_district_type":null,"city_district_type_full":null,"city_district":null,"settlement_fias_id":null,"settlement_kladr_id":null,"settlement_with_type":null,"settlement_type":null,"settlement_type_full":null,"settlement":null,"street_fias_id":null,"street_kladr_id":null,"street_with_type":null,"street_type":null,"street_type_full":null,"street":null,"house_fias_id":null,"house_kladr_id":null,"house_type":null,"house_type_full":null,"house":null,"block_type":null,"block_type_full":null,"block":null,"flat_type":null,"flat_type_full":null,"flat":null,"flat_area":null,"square_meter_price":null,"flat_price":null,"postal_box":null,"fias_id":"c1cfe4b9-f7c2-423c-abfa-6ed1c05a15c5","fias_code":null,"fias_level":"4","fias_actuality_state":null,"kladr_id":"6100000100000","geoname_id":null,"capital_marker":"2","okato":"60401000000","oktmo":"60701000001","tax_office":null,"tax_office_legal":null,"timezone":null,"geo_lat":null,"geo_lon":null,"beltway_hit":null,"beltway_distance":null,"metro":null,"qc_geo":null,"qc_complete":null,"qc_house":null,"history_values":null,"unparsed_parts":null,"source":null,"qc":null}}}}

в итоге вылетает 500

**Comment by akurutin** [comment]
Исправлено после выкладки.
Поле active не может быть null (это я про вложенную сущность адреса).

```
{
   "name":"Test",
   "shopTypes":[
      {
         "id":4
      }
   ],
   "counterparty":{
      "id":1
   },
   "active":true,
   "address":{
      "id":null,
      "version":null,
      "active":true,
      "address":"г Ростов-на-Дону",
      "comment":"Test",
      "suggestion":{
         "value":"г Ростов-на-Дону",
         "unrestricted_value":"Ростовская обл, г Ростов-на-Дону",
         "data":{
            "postal_code":null,
            "country":"Россия",
            "country_iso_code":"RU",
            "federal_district":null,
            "region_fias_id":"f10763dc-63e3-48db-83e1-9c566fe3092b",
            "region_kladr_id":"6100000000000",
            "region_iso_code":"RU-ROS",
            "region_with_type":"Ростовская обл",
            "region_type":"обл",
            "region_type_full":"область",
            "region":"Ростовская",
            "area_fias_id":null,
            "area_kladr_id":null,
            "area_with_type":null,
            "area_type":null,
            "area_type_full":null,
            "area":null,
            "city_fias_id":"c1cfe4b9-f7c2-423c-abfa-6ed1c05a15c5",
            "city_kladr_id":"6100000100000",
            "city_with_type":"г Ростов-на-Дону",
            "city_type":"г",
            "city_type_full":"город",
            "city":"Ростов-на-Дону",
            "city_area":null,
            "city_district_fias_id":null,
            "city_district_kladr_id":null,
            "city_district_with_type":null,
            "city_district_type":null,
            "city_district_type_full":null,
            "city_district":null,
            "settlement_fias_id":null,
            "settlement_kladr_id":null,
            "settlement_with_type":null,
            "settlement_type":null,
            "settlement_type_full":null,
            "settlement":null,
            "street_fias_id":null,
            "street_kladr_id":null,
            "street_with_type":null,
            "street_type":null,
            "street_type_full":null,
            "street":null,
            "house_fias_id":null,
            "house_kladr_id":null,
            "house_type":null,
            "house_type_full":null,
            "house":null,
            "block_type":null,
            "block_type_full":null,
            "block":null,
            "flat_type":null,
            "flat_type_full":null,
            "flat":null,
            "flat_area":null,
            "square_meter_price":null,
            "flat_price":null,
            "postal_box":null,
            "fias_id":"c1cfe4b9-f7c2-423c-abfa-6ed1c05a15c5",
            "fias_code":null,
            "fias_level":"4",
            "fias_actuality_state":null,
            "kladr_id":"6100000100000",
            "geoname_id":null,
            "capital_marker":"2",
            "okato":"60401000000",
            "oktmo":"60701000001",
            "tax_office":null,
            "tax_office_legal":null,
            "timezone":null,
            "geo_lat":null,
            "geo_lon":null,
            "beltway_hit":null,
            "beltway_distance":null,
            "metro":null,
            "qc_geo":null,
            "qc_complete":null,
            "qc_house":null,
            "history_values":null,
            "unparsed_parts":null,
            "source":null,
            "qc":null
         }
      }
   }
}
```
